import Head from 'next/head';
import Navigation from '@/components/dumb/Navigation/Navigation.jsx';
import HomepagePanel from '@/components/dumb/HomepagePanel/HomepagePanel';
import panels from './home.json';

function Home() {
  return (
    <>
      <Head>
        <title>Smart Camping</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/images/favicon/favicon.ico' />
      </Head>
      <main>
        {panels.map((item) => (
          <HomepagePanel
            key={item.id}
            backgroundImage={item.backgroundImage}
            textAlign={item.textAlign}
            title={item.title}
            subTitle={item.subTitle}
            href={item.href}
          />
        ))}
      </main>
    </>
  );
}
export default Navigation(Home);
